/**
 * Interactive flowchart node definitions.
 * Maps every step from the 3 Figma flowcharts to code, endpoints, and build status.
 * This is the source of truth for what's built vs what's missing.
 */

export type NodeStatus = 'built' | 'partial' | 'not_built';
export type NodeType = 'action' | 'decision' | 'agent' | 'system' | 'human' | 'external';

export interface FlowchartNode {
  id: string;
  label: string;
  type: NodeType;
  status: NodeStatus;
  description: string;
  /** Relevant source files */
  files: string[];
  /** API endpoints related to this step */
  endpoints: string[];
  /** What's done */
  done: string[];
  /** What's still needed */
  todo: string[];
  /** Depends on these node IDs */
  depends_on: string[];
}

export interface FlowchartDefinition {
  id: string;
  label: string;
  description: string;
  nodes: FlowchartNode[];
}

// ══════════════════════════════════════════════════════════════
// FLOWCHART 1: Lead Generation Pipeline
// ══════════════════════════════════════════════════════════════

export const LEAD_GEN_FLOWCHART: FlowchartDefinition = {
  id: 'lead-gen',
  label: 'Lead Generation Pipeline',
  description: 'SP signup → scrape → demo gen → QC → assign to salesperson with ready demo',
  nodes: [
    {
      id: 'sp-signup',
      label: 'SP signs up',
      type: 'human',
      status: 'built',
      description: 'Salesperson creates account with name, PIN, and area postcode.',
      files: [
        'apps/sales-dashboard/src/app/api/auth/signup/route.ts',
        'apps/sales-dashboard/src/app/login/page.tsx',
        'apps/mobile-api/src/routes/auth.ts',
        'apps/ios/salesflow/SalesFlow/AuthStore.swift',
      ],
      endpoints: [
        'POST /api/auth/signup — create SP account',
        'POST /api/auth/login — SP login with PIN',
      ],
      done: ['Signup API (sales-dashboard)', 'Login API (sales-dashboard + mobile-api)', 'iOS auth flow'],
      todo: [],
      depends_on: [],
    },
    {
      id: 'location-submitted',
      label: 'Location submitted',
      type: 'action',
      status: 'built',
      description: 'SP submits their area postcode during signup. Used for lead matching.',
      files: ['apps/sales-dashboard/src/app/api/auth/signup/route.ts'],
      endpoints: ['POST /api/auth/signup — area_postcode field'],
      done: ['area_postcode stored in sales_users table'],
      todo: [],
      depends_on: ['sp-signup'],
    },
    {
      id: 'pipeline-triggers',
      label: 'Pipeline triggers immediately',
      type: 'system',
      status: 'partial',
      description: 'Pipeline should auto-trigger when SP submits location. Currently requires manual trigger.',
      files: [
        'src/runtime/pipeline-engine.ts',
        'src/pipeline/scheduler.ts',
        'scripts/test-live-pipeline.ts',
      ],
      endpoints: [
        'POST /api/jobs/:id/run — manual trigger',
        'POST /api/jobs/:id/trigger — scheduler trigger',
      ],
      done: ['Manual pipeline trigger via API', 'Scheduler-based trigger', 'Test script trigger'],
      todo: ['Auto-trigger on SP signup', 'Webhook from signup → pipeline start'],
      depends_on: ['location-submitted'],
    },
    {
      id: 'agent-scraper',
      label: 'AGENT-01: Scraper',
      type: 'agent',
      status: 'built',
      description: 'Lead Scout + Lead Profiler. Searches Google Places by vertical + location, then scrapes websites and Instagram.',
      files: [
        'src/agents/outreach/leadScoutAgent.ts',
        'src/agents/outreach/leadProfilerAgent.ts',
      ],
      endpoints: [],
      done: [
        'Google Places text search by vertical',
        'Place Details enrichment (photos, reviews, hours, phone)',
        'Website scraping via Playwright',
        'Instagram scraping via Apify',
        'Brand colour extraction from photos',
      ],
      todo: [],
      depends_on: ['pipeline-triggers'],
    },
    {
      id: 'google-places',
      label: 'Google Places API',
      type: 'external',
      status: 'built',
      description: 'Text search + Place Details for each vertical in the SP area.',
      files: ['src/agents/outreach/leadScoutAgent.ts'],
      endpoints: ['Google Places Text Search API', 'Google Places Details API'],
      done: ['Multi-vertical search', 'Place Details with photos/reviews/hours'],
      todo: [],
      depends_on: ['agent-scraper'],
    },
    {
      id: 'apify-instagram',
      label: 'Apify Instagram scrape',
      type: 'external',
      status: 'built',
      description: 'Scrapes Instagram profiles for social presence data.',
      files: ['src/agents/outreach/leadProfilerAgent.ts'],
      endpoints: ['Apify Instagram Profile Scraper'],
      done: ['Instagram profile scraping', 'Follower count extraction'],
      todo: [],
      depends_on: ['agent-scraper'],
    },
    {
      id: 'business-profile',
      label: 'Business profile built',
      type: 'system',
      status: 'built',
      description: 'Brand Analyser extracts colours/fonts/assets. Brand Intelligence generates tone, USPs, headline via Claude.',
      files: [
        'src/agents/outreach/brandAnalyser.ts',
        'src/agents/outreach/brandIntelligence.ts',
      ],
      endpoints: ['OpenRouter API (Claude) for brand intelligence'],
      done: ['Photo colour palette extraction', 'Font detection', 'AI brand tone analysis', 'USP generation', 'Headline generation'],
      todo: [],
      depends_on: ['agent-scraper'],
    },
    {
      id: 'generation-cap',
      label: 'On-demand generation\n5 per day cap',
      type: 'system',
      status: 'not_built',
      description: 'Rate limit: max 5 demo site generations per day per SP.',
      files: ['src/runtime/pipeline-engine.ts'],
      endpoints: [],
      done: ['Budget enforcement exists (cost-based)'],
      todo: ['Per-SP daily generation cap (count-based)', 'Cap enforcement in pipeline engine'],
      depends_on: ['business-profile'],
    },
    {
      id: 'agent-generation',
      label: 'AGENT-02: Generation',
      type: 'agent',
      status: 'partial',
      description: 'Brief Generator creates spec, Site Composer generates full HTML/CSS demo via Claude.',
      files: [
        'src/agents/outreach/briefGenerator.ts',
        'src/agents/outreach/siteComposerAgent.ts',
        'src/agents/outreach/aiComposer.ts',
      ],
      endpoints: ['OpenRouter API (Claude) for site generation'],
      done: ['Brief generator agent', 'AI composer (Claude → HTML/CSS)', 'Site composer agent wrapper'],
      todo: ['Composer using full brand data from working memory', 'Template system for consistent quality'],
      depends_on: ['generation-cap'],
    },
    {
      id: 'claude-demo',
      label: 'Claude API generates\ndemo HTML/CSS',
      type: 'external',
      status: 'built',
      description: 'Claude Sonnet 4 via OpenRouter generates the full demo website.',
      files: ['src/agents/outreach/aiComposer.ts'],
      endpoints: ['OpenRouter /chat/completions — anthropic/claude-sonnet-4'],
      done: ['HTML/CSS generation from brief', 'Responsive design'],
      todo: ['Use brand colours/tone from working memory'],
      depends_on: ['agent-generation'],
    },
    {
      id: 'agent-qc',
      label: 'AGENT-03: QC Agent',
      type: 'agent',
      status: 'built',
      description: 'LLM Critic evaluates demo quality. Reflection loop retries if score < 0.7.',
      files: [
        'src/agents/outreach/siteQaAgent.ts',
        'src/evaluation/critic-model.ts',
        'src/evaluation/reflection-loop.ts',
      ],
      endpoints: ['OpenRouter API (Claude) for critic evaluation'],
      done: ['Site QA agent', 'LLM Critic (Claude evaluates sales effectiveness)', 'Reflection loop with critique→retry', 'Force-accept with human review flag'],
      todo: [],
      depends_on: ['claude-demo'],
    },
    {
      id: 'qc-decision',
      label: 'QC score >= 0.7?',
      type: 'decision',
      status: 'built',
      description: 'If critic score >= 0.7, proceed. If < 0.7, retry up to 3 times. Force-accept best after 3.',
      files: ['src/evaluation/reflection-loop.ts'],
      endpoints: [],
      done: ['Threshold check', 'Max 3 retries', 'Force-accept with flag'],
      todo: [],
      depends_on: ['agent-qc'],
    },
    {
      id: 'screenshot-r2',
      label: 'Screenshot saved to R2',
      type: 'system',
      status: 'not_built',
      description: 'Screenshot of the generated demo saved to Cloudflare R2 for preview thumbnails.',
      files: [],
      endpoints: ['Cloudflare R2 PUT'],
      done: [],
      todo: ['Puppeteer/Playwright screenshot of generated HTML', 'R2 upload', 'Store R2 URL in lead data'],
      depends_on: ['qc-decision'],
    },
    {
      id: 'demo-supabase',
      label: 'demo_records written\nto Supabase',
      type: 'system',
      status: 'not_built',
      description: 'Demo site data written to Supabase for cross-app access.',
      files: [],
      endpoints: ['Supabase REST API — demo_records table'],
      done: [],
      todo: ['Supabase client in pipeline', 'demo_records table schema', 'Write demo HTML + metadata after QC pass'],
      depends_on: ['screenshot-r2'],
    },
    {
      id: 'lead-sp-queue',
      label: 'Lead added to SP queue',
      type: 'system',
      status: 'built',
      description: 'Lead Assigner matches lead to nearest SP by postcode and writes to lead_assignments.',
      files: [
        'src/agents/outreach/leadAssignerAgent.ts',
      ],
      endpoints: [],
      done: ['Postcode proximity matching', 'Lead assignment with enriched notes JSON', 'Idempotent assignment'],
      todo: ['Push notification to SP app'],
      depends_on: ['demo-supabase'],
    },
    {
      id: 'sp-onboarding',
      label: 'SP onboarding completes',
      type: 'human',
      status: 'partial',
      description: 'SP completes onboarding and can see leads in dashboard/app.',
      files: [
        'apps/sales-dashboard/src/app/dashboard/page.tsx',
        'apps/ios/salesflow/SalesFlow/LeadsView.swift',
      ],
      endpoints: ['GET /api/leads — list assigned leads'],
      done: ['Dashboard lead list', 'iOS lead list', 'Lead detail views'],
      todo: ['Onboarding tutorial flow', 'First-lead celebration'],
      depends_on: ['lead-sp-queue'],
    },
    {
      id: 'dashboard-unlocks',
      label: 'Dashboard unlocks\nleads ready on map',
      type: 'system',
      status: 'built',
      description: 'SP sees leads as pins on a map with full business data.',
      files: [
        'apps/sales-dashboard/src/app/map/page.tsx',
        'apps/ios/salesflow/SalesFlow/LeadsMapView.swift',
      ],
      endpoints: ['GET /api/leads — with geocoded coordinates'],
      done: ['Map view (sales dashboard)', 'Map view (iOS with MapKit)', 'Route planning'],
      todo: [],
      depends_on: ['sp-onboarding'],
    },
    {
      id: 'lead-available',
      label: 'Lead available?',
      type: 'decision',
      status: 'not_built',
      description: 'Check if a lead is still available (not claimed by another SP).',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Lead availability check', 'Real-time availability status'],
      depends_on: ['dashboard-unlocks'],
    },
    {
      id: 'sp-claims-lead',
      label: 'SP claims lead',
      type: 'human',
      status: 'not_built',
      description: 'SP taps to claim a lead from the map. Lead becomes exclusively theirs.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Claim API endpoint', 'Optimistic lock to prevent double-claim', 'iOS claim UI'],
      depends_on: ['lead-available'],
    },
    {
      id: 'lead-transfer',
      label: 'Request lead transfer\nin-app search',
      type: 'human',
      status: 'not_built',
      description: 'SP can request to transfer a lead or search for leads in other areas.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Transfer request API', 'Transfer approval flow', 'In-app lead search'],
      depends_on: ['lead-available'],
    },
  ],
};

// ══════════════════════════════════════════════════════════════
// FLOWCHART 2: Pitch to Fulfilment
// ══════════════════════════════════════════════════════════════

export const PITCH_FULFIL_FLOWCHART: FlowchartDefinition = {
  id: 'pitch-fulfil',
  label: 'Pitch to Fulfilment',
  description: 'SP visits → demo shown → owner response → sale or rejection → fulfilment → client portal',
  nodes: [
    {
      id: 'sp-visits',
      label: 'SP visits business',
      type: 'human',
      status: 'partial',
      description: 'Salesperson physically visits the business. GPS + dwell time validated (200m, 2 min).',
      files: [
        'apps/ios/salesflow/SalesFlow/LeadDetailView.swift',
        'apps/mobile-api/src/routes/visits.ts',
      ],
      endpoints: [
        'POST /leads/:id/visit — start visit session',
        'POST /visits/:id/gps — GPS ping during visit',
      ],
      done: ['Visit tracking UI (iOS)', 'Visit session API'],
      todo: ['GPS validation (200m radius)', 'Dwell time enforcement (2 min minimum)'],
      depends_on: [],
    },
    {
      id: 'demo-shown',
      label: 'Demo shown on phone',
      type: 'human',
      status: 'built',
      description: 'SP shows the generated demo site to the business owner on their phone.',
      files: [
        'apps/ios/salesflow/SalesFlow/ClientPresentationView.swift',
        'apps/ios/salesflow/SalesFlow/DemoSiteCache.swift',
      ],
      endpoints: [],
      done: ['Full-screen client presentation mode', 'Demo site caching for offline', 'Share button'],
      todo: [],
      depends_on: ['sp-visits'],
    },
    {
      id: 'owner-response',
      label: 'Owner response?',
      type: 'decision',
      status: 'not_built',
      description: 'Business owner either wants to buy (interested) or declines (rejection).',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Outcome capture UI in iOS app', 'Interested/Rejected flow branching'],
      depends_on: ['demo-shown'],
    },
    {
      id: 'qr-capture',
      label: 'QR code or contact capture',
      type: 'action',
      status: 'not_built',
      description: 'If interested: capture business owner contact via QR code scan or manual entry.',
      files: ['apps/ios/salesflow/SalesFlow/DemoShareSheet.swift'],
      endpoints: [],
      done: ['QR code generation for demo link', 'AirDrop share'],
      todo: ['Contact capture form', 'QR scan to capture owner details'],
      depends_on: ['owner-response'],
    },
    {
      id: 'link-sent',
      label: 'Link sent via SMS or email',
      type: 'system',
      status: 'not_built',
      description: 'Demo link + payment link sent to business owner via SMS or email.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['SMS sending (Twilio)', 'Email sending', 'Demo link with tracking', 'Payment link inclusion'],
      depends_on: ['qr-capture'],
    },
    {
      id: 'payment-received',
      label: '£350 received?',
      type: 'decision',
      status: 'not_built',
      description: 'Check if the £350 payment has been received via Stripe.',
      files: ['apps/sales-dashboard/src/app/api/payments'],
      endpoints: ['Stripe Checkout Session', 'Stripe Webhook — payment_intent.succeeded'],
      done: ['Stripe Connect setup in sales dashboard'],
      todo: ['Payment link generation', 'Webhook handler', 'Payment status tracking'],
      depends_on: ['link-sent'],
    },
    {
      id: 'client-wizard',
      label: 'Client completes wizard\npreferences, photos, notes',
      type: 'human',
      status: 'not_built',
      description: 'Client fills in preferences, uploads photos, adds notes for the full site build.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Client-facing wizard UI', 'Photo upload', 'Preference form', 'Notes field'],
      depends_on: ['payment-received'],
    },
    {
      id: 'stripe-payment-link',
      label: 'Stripe payment link sent',
      type: 'system',
      status: 'not_built',
      description: 'If payment not yet received, send Stripe payment link to client.',
      files: [],
      endpoints: ['Stripe Payment Links API'],
      done: [],
      todo: ['Payment link generation', 'SMS/email delivery'],
      depends_on: ['payment-received'],
    },
    {
      id: 'fulfilment-pipeline',
      label: 'FULFILMENT PIPELINE',
      type: 'system',
      status: 'not_built',
      description: 'Triggered by £350 payment. Generates full production site from wizard data + all prior intelligence.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Fulfilment pipeline definition', 'Wizard data → Claude API', 'Full site generation using demo + preferences'],
      depends_on: ['client-wizard'],
    },
    {
      id: 'full-site-gen',
      label: 'Full site generated',
      type: 'agent',
      status: 'not_built',
      description: 'Claude generates production-quality site from wizard data + brand intelligence + demo.',
      files: ['src/agents/outreach/aiComposer.ts'],
      endpoints: ['OpenRouter API (Claude)'],
      done: ['AI composer exists for demos'],
      todo: ['Production-quality generation mode', 'Wizard data integration', 'Multi-page support'],
      depends_on: ['fulfilment-pipeline'],
    },
    {
      id: 'vercel-deploy',
      label: 'Deployed via Vercel MCP',
      type: 'system',
      status: 'not_built',
      description: 'Generated site deployed to Vercel automatically.',
      files: [],
      endpoints: ['Vercel API — deployment'],
      done: [],
      todo: ['Vercel MCP integration', 'Automatic deployment from pipeline', 'Subdomain assignment'],
      depends_on: ['full-site-gen'],
    },
    {
      id: 'domain-porkbun',
      label: 'Domain registered on Porkbun',
      type: 'system',
      status: 'not_built',
      description: 'Custom domain registered via Porkbun API and pointed to Vercel.',
      files: [],
      endpoints: ['Porkbun API — domain registration'],
      done: [],
      todo: ['Porkbun API integration', 'Domain availability check', 'DNS configuration'],
      depends_on: ['vercel-deploy'],
    },
    {
      id: 'ssl-provision',
      label: 'SSL auto-provisioned',
      type: 'system',
      status: 'not_built',
      description: 'SSL certificate automatically provisioned via Vercel/Cloudflare.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Automatic SSL via Vercel'],
      depends_on: ['domain-porkbun'],
    },
    {
      id: 'stripe-invoice',
      label: 'Stripe invoice generated',
      type: 'system',
      status: 'not_built',
      description: 'Invoice generated and sent to client via Stripe.',
      files: [],
      endpoints: ['Stripe Invoices API'],
      done: [],
      todo: ['Invoice generation', 'Auto-send to client email'],
      depends_on: ['ssl-provision'],
    },
    {
      id: 'confirmation-email',
      label: 'Confirmation email to client\nwith live URL',
      type: 'system',
      status: 'not_built',
      description: 'Email sent to client with their live website URL.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Email template', 'Send via transactional email service'],
      depends_on: ['stripe-invoice'],
    },
    {
      id: 'sp-commission',
      label: 'SP commission marked pending\n£20-70 based on logged pitches',
      type: 'system',
      status: 'not_built',
      description: 'SP commission calculated based on pitch history and marked as pending payout.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Commission calculation logic', 'Pitch-count based tiers', 'Payout tracking'],
      depends_on: ['confirmation-email'],
    },
    {
      id: 'queue-replenish',
      label: 'Lead queue replenished\nautomatically',
      type: 'system',
      status: 'not_built',
      description: 'After a sale, new leads auto-generated for the SP area.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Auto-trigger pipeline on sale', 'Replenishment logic'],
      depends_on: ['sp-commission'],
    },
    {
      id: 'client-portal',
      label: 'CLIENT PORTAL ACTIVE',
      type: 'system',
      status: 'not_built',
      description: 'Client gets access to their portal for managing their site.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Client portal app', 'Login system', 'Site management UI'],
      depends_on: ['queue-replenish'],
    },
    {
      id: 'tier2-changes',
      label: 'Tier 2: design changes\n1 per month via Claude API',
      type: 'system',
      status: 'not_built',
      description: 'Clients can request 1 design change per month via Claude.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Change request form', 'Claude-powered edit generation', 'Monthly quota tracking'],
      depends_on: ['client-portal'],
    },
    {
      id: 'tier1-selfservice',
      label: 'Tier 1: self-service\nlocal AI on Mac Mini',
      type: 'system',
      status: 'not_built',
      description: 'Self-service editing via local AI running on Mac Mini.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Local AI setup', 'Self-service editing UI', 'Mac Mini deployment'],
      depends_on: ['client-portal'],
    },
    // Rejection path
    {
      id: 'pitch-outcome-logged',
      label: 'Pitch outcome logged',
      type: 'system',
      status: 'partial',
      description: 'Pitch result recorded — closed, rejected, or no-show.',
      files: ['src/memory/episodic-store.ts'],
      endpoints: ['PATCH /leads/:id/status'],
      done: ['Episodic memory records outcomes', 'Status update API'],
      todo: ['iOS outcome capture UI with structured data'],
      depends_on: ['owner-response'],
    },
    {
      id: 'voice-memo',
      label: 'Voice memo submitted',
      type: 'human',
      status: 'not_built',
      description: 'SP records voice memo about the pitch for learning data.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Voice recording in iOS', 'Upload to API', 'Transcription'],
      depends_on: ['pitch-outcome-logged'],
    },
    {
      id: 'gps-dwell-validate',
      label: 'GPS + dwell time validated\n200m, 2 min minimum',
      type: 'system',
      status: 'not_built',
      description: 'Verify SP was physically at the business for at least 2 minutes.',
      files: ['apps/mobile-api/src/routes/visits.ts'],
      endpoints: ['POST /visits/:id/gps'],
      done: ['Visit session tracking exists'],
      todo: ['GPS radius validation (200m)', 'Dwell time check (2 min)', 'Anti-fraud'],
      depends_on: ['pitch-outcome-logged'],
    },
    {
      id: 'rejection-captured',
      label: 'Rejection reason captured',
      type: 'system',
      status: 'not_built',
      description: 'Structured rejection reason stored for learning.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Rejection reason dropdown', 'Store in episodes', 'Feed to strategy learner'],
      depends_on: ['gps-dwell-validate'],
    },
    {
      id: 'commission-enhancement',
      label: 'Commission enhancement\ncalculated for next close',
      type: 'system',
      status: 'not_built',
      description: 'Rejections increase commission rate on next sale to reward effort.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Enhancement calculation', 'Commission tier adjustment'],
      depends_on: ['rejection-captured'],
    },
  ],
};

// ══════════════════════════════════════════════════════════════
// FLOWCHART 3: Self-Learning Loop
// ══════════════════════════════════════════════════════════════

export const LEARNING_LOOP_FLOWCHART: FlowchartDefinition = {
  id: 'learning-loop',
  label: 'Self-Learning Loop',
  description: 'Critic evaluation → episodic memory → outcome attachment → strategy discovery → prompt injection',
  nodes: [
    {
      id: 'agent-produces-output',
      label: 'Agent produces output',
      type: 'agent',
      status: 'built',
      description: 'Any pipeline agent (Brand Intel, Composer, etc.) produces its output.',
      files: ['src/runtime/pipeline-engine.ts', 'src/pipeline/agentRuntime.ts'],
      endpoints: [],
      done: ['Agent execution via registry', 'Output stored as artifacts'],
      todo: [],
      depends_on: [],
    },
    {
      id: 'critic-evaluates',
      label: 'LLM Critic evaluates',
      type: 'agent',
      status: 'built',
      description: 'Claude evaluates the output: "Would this close a sale?"',
      files: ['src/evaluation/critic-model.ts'],
      endpoints: ['OpenRouter API — Claude for evaluation'],
      done: ['LLM Critic with structured output', 'Score + prediction + critique', 'Heuristic fallback'],
      todo: [],
      depends_on: ['agent-produces-output'],
    },
    {
      id: 'score-threshold',
      label: 'Score >= 0.7?',
      type: 'decision',
      status: 'built',
      description: 'If score >= 0.7, accept. Otherwise retry with feedback.',
      files: ['src/evaluation/reflection-loop.ts'],
      endpoints: [],
      done: ['Threshold check', 'Configurable via CRITIC_THRESHOLD env'],
      todo: [],
      depends_on: ['critic-evaluates'],
    },
    {
      id: 'critique-injected',
      label: 'Critique injected\ninto agent input',
      type: 'system',
      status: 'built',
      description: 'Specific weaknesses + suggestions injected into agent prompt for retry.',
      files: ['src/evaluation/reflection-loop.ts'],
      endpoints: [],
      done: ['Critique feedback as _criticFeedback in upstream artifacts', 'Strengths preserved, weaknesses addressed'],
      todo: [],
      depends_on: ['score-threshold'],
    },
    {
      id: 'agent-retries',
      label: 'Agent retries with feedback',
      type: 'agent',
      status: 'built',
      description: 'Agent re-runs with critic feedback. Max 3 iterations.',
      files: ['src/evaluation/reflection-loop.ts'],
      endpoints: [],
      done: ['Max 3 retries', 'Force-accept best after exhaustion', 'Human review flag'],
      todo: [],
      depends_on: ['critique-injected'],
    },
    {
      id: 'episode-recorded',
      label: 'Episode recorded',
      type: 'system',
      status: 'built',
      description: 'Full pipeline run recorded with all context — agent outputs, critic scores, working memory.',
      files: ['src/memory/episodic-store.ts'],
      endpoints: [],
      done: ['Episode creation on run start', 'Critic scores stored per iteration', 'Working memory snapshot', 'Cost tracking'],
      todo: [],
      depends_on: ['agent-retries'],
    },
    {
      id: 'outcome-attached',
      label: 'Pitch outcome attached',
      type: 'system',
      status: 'built',
      description: 'When SP reports pitch result, outcome linked to episode.',
      files: ['src/memory/episodic-store.ts'],
      endpoints: [],
      done: ['recordOutcome() method', 'closed/rejected/no_show + amount + salesperson'],
      todo: ['API endpoint to receive outcomes from iOS app'],
      depends_on: ['episode-recorded'],
    },
    {
      id: 'attribution-engine',
      label: 'Attribution Engine',
      type: 'system',
      status: 'not_built',
      description: 'Traces credit/blame from outcome back through pipeline agents.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Attribution calculation', 'Agent-level credit scoring', 'Store in episode'],
      depends_on: ['outcome-attached'],
    },
    {
      id: 'strategy-ranker',
      label: 'Strategy Ranker (nightly)',
      type: 'system',
      status: 'not_built',
      description: 'Analyses episodes with outcomes, discovers what design choices close sales.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['Nightly batch job', 'Group by vertical + design parameters', 'Statistical significance check', 'Strategy promotion lifecycle'],
      depends_on: ['attribution-engine'],
    },
    {
      id: 'strategic-memory',
      label: 'Strategic Memory updated',
      type: 'system',
      status: 'not_built',
      description: '"Barbers with trust-blue hero and reviews close at 41%" stored as a strategy.',
      files: [],
      endpoints: [],
      done: [],
      todo: ['strategies table', 'Strategy CRUD', 'Lifecycle: new → testing → active → champion → deprecated'],
      depends_on: ['strategy-ranker'],
    },
    {
      id: 'strategy-injected',
      label: 'Strategies injected\ninto next pipeline run',
      type: 'system',
      status: 'partial',
      description: 'Relevant strategies injected into working memory for future runs.',
      files: ['src/runtime/pipeline-engine.ts', 'src/runtime/working-memory.ts'],
      endpoints: [],
      done: ['StrategyProvider interface', 'Strategy injection into working memory', 'strategyContext field on agent input'],
      todo: ['Connect to strategic memory store', 'Populate from real data'],
      depends_on: ['strategic-memory'],
    },
  ],
};

export const ALL_FLOWCHARTS: FlowchartDefinition[] = [
  LEAD_GEN_FLOWCHART,
  PITCH_FULFIL_FLOWCHART,
  LEARNING_LOOP_FLOWCHART,
];
